import TestimonialImage from "./TestimonialImage";

import angie from "../../assets/angie.png";
import lebo from "../../assets/lebo.webp";
import mpho from "../../assets/mpho.jpg";
import thabo from "../../assets/thabo.webp";

import test1 from "../../assets/Layer 1.png";
import test3 from "../../assets/Layer 3.png";
import test4 from "../../assets/Layer 4.png";
import test6 from "../../assets/Layer 6.png";
import test7 from "../../assets/Layer 7.png";
import test8 from "../../assets/Layer 8.png";
import test9 from "../../assets/Layer 9.png";
import test11 from "../../assets/layer 11.png";
import test12 from "../../assets/layer 12.png";
import test13 from "../../assets/layer 13.png";
import test14 from "../../assets/layer 14.png";
import test15 from "../../assets/layer 15.png";
import test16 from "../../assets/layer 16.png";
import test17 from "../../assets/layer 17.png";
import test18 from "../../assets/layer 18.png";
import test19 from "../../assets/layer 19.png";
import test20 from "../../assets/Layer 20.png";

/**
 * `alt` is doing real work here, not accessibility box-ticking: a wall of
 * screenshots is otherwise invisible to search engines, so each one describes
 * the result it shows.
 */
export const TESTIMONIAL_IMAGES = [
  {
    src: test6,
    alt: "WhatsApp message from Angie, a South African estate agent, reporting 20 seller leads at R10 each",
    credit: { img: angie, name: "Angie", caption: "20 leads so far at R10 each" },
  },
  {
    src: test9,
    alt: "Lebo reporting 65 or more seller leads collected at R9 each in three days",
    credit: {
      img: lebo,
      name: "Lebo",
      caption: "So far collected 65+ leads at R9 each",
    },
  },
  { src: test20, alt: "Estate agent message confirming booked listing appointments from EstateKit campaigns" },
  { src: test19, alt: "Agent reporting new seller enquiries generated by Facebook and Instagram ads" },
  { src: test18, alt: "Screenshot of an agent confirming a signed mandate from a campaign lead" },
  { src: test17, alt: "South African estate agent reporting a full diary of listing appointments" },
  { src: test16, alt: "Agent message showing inbound seller leads arriving the same week ads launched" },
  { src: test15, alt: "Estate agent confirming valuation appointments booked from EstateKit leads" },
  { src: test14, alt: "Agent reporting low cost per seller lead on their EstateKit campaign" },
  { src: test13, alt: "Screenshot of a South African agent celebrating a new sole mandate" },
  { src: test12, alt: "Estate agent message about consistent weekly seller enquiries" },
  { src: test11, alt: "Agent confirming appointments booked without any cold calling" },
  { src: test1, alt: "Estate agent reporting listing appointments generated in their suburb" },
  { src: test3, alt: "Agent message showing seller leads delivered by EstateKit" },
  {
    src: test8,
    alt: "Thabo, a South African estate agent, reporting more than 30 seller leads at R10 each",
    credit: { img: thabo, name: "Thabo", caption: "30+ leads at R10 each" },
  },
  {
    src: test7,
    alt: "Mpho reporting 48 seller leads at R9 each from EstateKit campaigns",
    credit: { img: mpho, name: "Mpho", caption: "48 leads at R9 each" },
  },
  { src: test4, alt: "Estate agent confirming closed business traced back to EstateKit leads" },
];

export default function TestimonialProof({
  heading = "Agents in your area using this system are getting results like these RIGHT NOW...",
}) {
  return (
    <section className="max-w-4xl px-4 sm:px-6 mx-auto mb-12 mt-12">
      <p className="font-bold text-lg sm:text-xl md:text-2xl text-center mb-8">
        {heading}
      </p>
      <div className="flex flex-wrap gap-2 justify-center">
        {TESTIMONIAL_IMAGES.map((t, i) => (
          <TestimonialImage key={i} {...t} />
        ))}
      </div>
    </section>
  );
}
